image: python:2.7

pipelines:
  default:
    - step:
        script:
          - pip install git+https://bitbucket.org/fenics-project/fiat.git@master
          - pip install git+https://bitbucket.org/fenics-project/ufl.git@master
          - pip install git+https://bitbucket.org/fenics-project/instant.git@master
          - pip install pytest
          - pip install -e .
          - cd test/unit
          - py.test .