version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory:  ~/ffc-test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install libboost-math-dev
            sudo pip install flake8 pydocstyle pytest --upgrade
      - run:
          name: Install FEniCS dependencies
          command: |
            pip install git+https://bitbucket.org/fenics-project/fiat.git --user
            pip install git+https://bitbucket.org/fenics-project/ufl.git --user
            pip install git+https://bitbucket.org/fenics-project/dijitso.git --user
      - run:
          name: Install FFC
          command: pip install -e .
      - run:
          name: Run flake8 tests
          command: python -m flake8 ffc/
      - run:
          name: Run pydocstyle tests
          command: python -m pydocstyle ffc/

      #- run:
      #    name: Install pybind factory
      #    command: pip install ./libs/ffc-factory/ --user
      #- run:
      #    name: Run unit tests
      #    command: |
      #      python -m pytest -v ./test/unit
      #      python -m pytest -v ./test/uflacs
      #- run:
      #    name: Run regression tests
      #    command: |
      #      cd test/regression
      #      python test.py
